account/urls.py
# blog.urls.py

from django.urls import path

from account import views


app_name = "account"
urlpatterns = [
    path(
        route='register/',
        view=views.account_register_view,
        name='register_url'
    ),

    path(
        route='login/',
        view=views.account_login_view,
        name='login_url'
    ),

    path(route='activate/<uidb64>/<token>/',
        view=views.account_activate_account_view,
        name='activate'),

    path(route='set-new-password/<uidb64>/<token>/',
        view=views.account_set_new_password_view,
        name='set_new_password'),

    path(route='reset-password/',
        view=views.account_reset_password_view,
        name='reset_password'),

    path(
        route='logout/',
        view=views.account_logout_view,
        name='logout_url'
    ),

    path(
        route='',
        view=views.account_dashboard,
        name="profile_url"
    )
]

core/urls.py
"""
core URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/4.0/topics/http/urls/
"""

import logging

from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from django.conf.urls.static import static
from django.contrib.auth.models import Group

admin.site.unregister(Group)


urlpatterns = [
    path("", include("account.urls", namespace="account")),
    path(settings.ADMIN_URL, admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        {% load static compress %}{% get_static_prefix as STATIC_PREFIX %}

        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% compress css %}
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}lib/css/bootstrap.min.css" />
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}lib/css/line-awesome.min.css" />
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}lib/css/owl.carousel.min.css" />

        <link rel="stylesheet" href="{{ STATIC_PREFIX }}css/main.css" />
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}css/theme.css" />
        {% endcompress css %}

        <link rel="icon" href="{{ STATIC_PREFIX }}img/favicon.png">
        <link rel="apple-touch-icon" href="{{ STATIC_PREFIX }}img/icon/apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="72x72" href="{{ STATIC_PREFIX }}img/icon/icon-72x72.png">
        <link rel="apple-touch-icon" sizes="114x114" href="{{ STATIC_PREFIX }}img/icon/icon-114x114.png">

        <title>
            {% block head_title %}
            {{ page_title|default_if_none:"Accueil"|capfirst }}
            {% endblock head_title %}
            &smid; Blogger
        </title>

    </head>

    <body>
        {% block body %}
            <div class="ugf-wrapper theme-bg">
                <div class="ugf-content-block">
                    <div class="logo">
                        <a href="/">
                            <img src="{{ STATIC_PREFIX }}img/logo/logo-dark.png" class="dark-logo" alt="{{ page_tile|title }}">
                        </a>
                    </div>

                    <div class="container-md">
                        <div class="row">
                            <div class="col-lg-7 offset-lg-5">
                                {% block body_content %}{% endblock body_content %}
                            </div>
                        </div>
                    </div>

                    {% block alternet_access %}
                    {% endblock alternet_access %}
                </div>

                <div class="ugf-sidebar flex-bottom ugf-sidebar-bg">
                    <div class="testimonial-carousel owl-carousel">
                        <div class="item">
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                            <h5 class="name">Ronna E. Gomez</h5>
                            <span class="designation">CEO, Google</span>
                        </div>
                        <div class="item">
                            <div class="quote">
                                <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                                <h5 class="name">Ronna E. Gomez</h5>
                                <span class="designation">CEO, Google</span>
                            </div>
                        </div>
                        <div class="item">
                            <div class="item">
                                <div class="quote">
                                    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                                    <h5 class="name">Ronna E. Gomez</h5>
                                    <span class="designation">CEO, Google</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clients">
                        <div class="client">
                            <img src="{{ STATIC_PREFIX }}img/client/1.png" class="img-fluid" alt="">
                        </div>
                    </div>
                </div>

                {% compress js %}
                <script type="text/javascript" src="{{ STATIC_PREFIX }}lib/js/jquery.min.js"></script>
                <script type="text/javascript" src="{{ STATIC_PREFIX }}lib/js/popper.min.js"></script>
                <script type="text/javascript" src="{{ STATIC_PREFIX }}lib/js/bootstrap.min.js"></script>
                <script type="text/javascript" src="{{ STATIC_PREFIX }}lib/js/owl.carousel.min.js"></script>

                <script type="text/javascript" src="{{ STATIC_PREFIX }}js/custom.js"></script>
                {% endcompress js %}
            </div>
        {% endblock body %}
    </body>
</html>

templates/index.html
{% extends '_base.html' %}

{% block body %}
    {% url "account:logout_url" as logout_url %}

    <div class="ugf-wrapper final-bg">

        <div class="final-content">
            
            {% include "includes/_message.html" %}

            <div class="icon">
                <img src="{{ STATIC_PREFIX }}img/check.png" alt="{{ page_title|slugify }}">
            </div>
            <h2>Complete Account</h2>
            <p>Hey <strong>{{ request.user.email|safe }}</strong> ! Welcome to Anfra, an amazing Interface waiting for you.</p>
            <a href="{{ logout_url }}" class="btn">Logout Now</a>
        </div>
    </div>
{% endblock body %}